services:
#    app.example:
#        class: AppBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    app.product.redis:
        class:  AppBundle\Service\Product
        arguments:  ["%redis%"]
